package persistence;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public interface DbBase {
	
	@FunctionalInterface
	public interface PstmProcessor {
		void process(PreparedStatement pstm) throws SQLException, DatabaseException;
	}
	
	@FunctionalInterface
	public interface ResultSetProcessor {
		void process(ResultSet rs) throws SQLException, DatabaseException;
	}
	
	@FunctionalInterface
	public interface ResultSetReturnProcessor<T> {
		T process(ResultSet rs) throws SQLException, DatabaseException;
	}
	
	public void connect(String path2DB);
	public void disconnect();
	public int executeUpdate(String sql);
	public void executeUpdatePrepStm(String sql, PstmProcessor pstmProcessor);
	public void executeUpdatePrepStm(String sql, int autoGeneratedKeys,
			PstmProcessor pstmProcessor);
	public void processResultSet(String sqlSelect, ResultSetProcessor rsProcessor);
	public <T> T processResultSet2Val(String sqlSelect,
			ResultSetReturnProcessor<T> rsReturnProcessor);
	public void processPrepResultSet(String sqlSelect, PstmProcessor pstmProcessor,
			ResultSetProcessor rsProcessor);
	public <T> T processPrepResultSet2Val(String sqlSelect, PstmProcessor pstmProcessor,
			ResultSetReturnProcessor<T> rsReturnProcessor);
	
}
